### ISSUE TITLE
Data sets we need to write paper

### ISSUE THREAD

**Issue by milanterlunen** [lit-mod-viz/middlemarch-critical-histories#36]
In order to write the paper we need the following data sets, all using the most recent version of the algorithm and parameters we've settled on. @JonathanReeve could you produce these and export them as an Excel (or equivalent) file? There's so many results floating around and I don't wanna use the wrong sets or mix up different ones!

- Chapter-by-chapter breakdown
	- Tally of *number* of quotes
	- Tally of *total word count* of quotes
	- Diachronic breakdown of the above (decade level is fine)
	- Specialist/non-specialist breakdown of the above
		- What numbers of *quotes* and *total word counts* are accounted for by GE-GHL Studies vs. other journals?
		- How many articles in corpus come from GE-GHL Studies vs. other journals?
	- Total number of words per chapter (to allow for normalisation of all the above)
- Breakdowns for Chapters 15 and 20
	- Can you create a spreadsheet reflecting the data behind the text browser? Would need to contain:
		- Tally of quotes per word (both the actual word and its unique number in the linear sequence), broken down by decade
		- Info about paragraph structure, i.e. at which word-numbers does a new paragraph begin?
- List of the top 25 keywords, synchronic and diachronic (by decade)

**Comment by JonathanReeve** [comment]
I hear you about the many results floating around. I did a lot of reorganizing, and now all the up-to-date notebooks are in `notebooks/`, while all the old and outdated analyses are in `old/`. These notebooks should have everything you're looking for, except for the diachronic MDWs, which are tracked in #32. Some of the numerical data in this list might not be directly copy-pasteable from the notebook, but I'll show you how to get it from the notebook, since it's really easy (and a lot easier than making an Excel spreadsheet with all this stuff).
