### ISSUE TITLE
CSVs for word/quote count per decade don't match the CSV for totals

### ISSUE THREAD

**Issue by milanterlunen** [lit-mod-viz/middlemarch-critical-histories#48]
Just comparing the numbers and this is my strong suspicion, since the numbers are much larger. Oddly, almost all the word-count figures are 11-13 times larger than the word counts - does that suggest an average word length of 11-13 characters? surely that's wrong...

@JonathanReeve can you check this and either create an uploaded csv with *word* counts for each decade, or if there's a deeper problem here let's discuss further!

**Comment by milanterlunen** [comment]
Update: the problem also applies to the number of *quotes*, where the diachronic breakdown is consistently 14-16 times larger than the CSV for totals. This can't be about character counts, so what on earth is going on here?!

**Comment by milanterlunen** [comment]
I'm uploading my Excel workbook - check the "Ratio" columns on each sheet in particular

**Comment by milanterlunen** [comment]
Just fyi, the numbers for the specialist vs non-specialist **word** counts do exactly match the numbers from the overall word counts CSV, whatever that signifies...

**Comment by JonathanReeve** [comment]
This was a dumb bug. It seems I wasn't properly making a copy of some rows, and so whenever I would run `diachronicAnalysis` it would actually append to the dataset itself. So running the notebook about 15 times made it so that it was just constantly appending to itself. This should be fixed now, as seen in cells 13 and 14 of [the notebook](https://github.com/lit-mod-viz/middlemarch-critical-histories/blob/c221165ae549cbed042359334b4f73703a8b97ec/notebooks/jstor-analysis.ipynb).
